#define PLUS                            1
#define MINUS                           2
#define MUL                             3
#define DIV                             4
#define OR                              5
#define AND                             6
#define DOT                             7
#define NOT                             8
#define KW_STRUCT                       9
#define TOK_ID                         10
#define LBRACE                         11
#define RBRACE                         12
#define KW_FUNC                        13
#define LPARENTHESES                   14
#define RPARENTHESES                   15
#define KW_WHILE                       16
#define KW_IF                          17
#define KW_ELIF                        18
#define KW_ELSE                        19
#define EQ                             20
#define KW_FOR                         21
#define SEMICOLON                      22
#define COMMA                          23
#define LBRACKET                       24
#define RBRACKET                       25
#define KW_NULL                        26
#define TOK_STRING                     27
#define TOK_INT                        28
