#define PLUS                            1
#define MINUS                           2
#define MUL                             3
#define DIV                             4
#define OR                              5
#define AND                             6
#define DOT                             7
#define NOT                             8
#define KW_FUNC                         9
#define ID                             10
#define LPARENTHESES                   11
#define RPARENTHESES                   12
#define LBRACE                         13
#define RBRACE                         14
#define KW_WHILE                       15
#define KW_IF                          16
#define KW_ELIF                        17
#define KW_ELSE                        18
#define KW_STRUCT                      19
#define COMMA                          20
#define LBRACKET                       21
#define RBRACKET                       22
#define EQ                             23
#define KW_NULL                        24
#define TOK_STRING                     25
#define TOK_INT                        26
#define TOK_ID                         27
