#define MUL                             1
#define DIV                             2
#define PLUS                            3
#define MINUS                           4
#define AND                             5
#define OR                              6
#define NOT                             7
#define RPARENTHESES                    8
#define NULL                            9
#define STRING                         10
#define INT                            11
#define ID                             12
#define LPARENTHESES                   13
